### PR TITLE
HSDO-748 Added checkbox on customize display page

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Allows the addition of an optional css file that mostly changes font sizes.

# Needed By (Date)
- 3/15

# Steps to Test

1. Checkout branch.
2. run database updates
3. view /admin/stanford-jumpstart/customize-design and confirm "Include BIG text " checkbox near bottom
4. check the box and save
5. confirm font sizes change.

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/HSDO-753
- https://github.com/SU-SWS/linky_clicky/pull/145

### CODE REVIEW

**Comment by pookmish** [comment]
Remaining CC issues are either false negatives or would require some refactoring of existing code - unrelated to the new features.

**Comment by boznik** [comment]
@pookmish i'm finding that stanford_jumpstart_home_typography.css is getting loaded but overwritten on a fresh jsa install and then updating to this code.

**Comment by pookmish** [comment]
I'm not sure i follow what you mean @boznik. 
Just in case, some background: I believe the desired effect is on new installs the file config will be checked and the file will be added. on existing installs, the option will be unchecked and the file will not be added. Joe has some css changes he has to perform after the merge of this. 
So I believe if the file is being added, we'll leave the front end to him :)

**Comment by boznik** [comment]
@pookmish , the file is definitely being added, but other css (such as jumpstart.css)is overriding the specificity. Are you saying the css is not complete, and this PR is only to test that the file gets added?

**Comment by pookmish** [comment]
mostly yeah. and that the checkbox functionality. the jumpstart.css is the file Joe will manipulate after merger and not related to this PR. Not sure if you want to review the CC fixes as well. there were several

**Comment by boznik** [comment]
Did you make changes affecting Npath and cyclomatic complexity? I see CC throwing up some noise but i'm not sure that we decided to fix that stuff in our dev chat?

**Comment by pookmish** [comment]
the Npath, cyclomatic and repeat were the items i didnt want to tackle with such a small task in the PR. I think we decided to not go back and fix old issues, but i didnt want to show 1300+ issues lol.

**Pull request merged**
